### ISSUE TITLE
Sprite Widget is missing

### ISSUE THREAD

**Issue by RUSshy** [texus/CTGUI#1]
Hello

Looks like the Sprite widget is missing: https://github.com/texus/TGUI/blob/0.8-dev/include/TGUI/Sprite.hpp

Is it intentional?

**Comment by texus** [comment]
This is intentional.
Sprite is not a widget but an internal class for rendering. Picture is the widget that you use to draw an image.

**Comment by RUSshy** [comment]
Oh ok, thanks!

I'm asking this because i wanted to render a sprite, i first looked at Picture, but in the C# binding it looks like i can't draw a specific region from a given Texture

**Comment by texus** [comment]
Yeah, this indeed seems to be lacking in CTGUI and TGUI.Net. I'll have a look if it can be implemented easily.

**Comment by texus** [comment]
Ah, it seems to exist in the texture class form SFML, you can pass a parameter after the filename.

**Comment by RUSshy** [comment]
Yes i saw it but i don't think that's efficient to load the texture multiple times, i'm trying to draw a Sprite so the texture is already loaded in memory

**Comment by texus** [comment]
You don't have to load it multiple times.
You load it to an Image class once and then you load a Texture given the Image and an IntRect.

**Comment by RUSshy** [comment]
That still look inefficient to me, or i probably don't correctly understand how SFML works, wich is probably that since i'm using it since few month only :p

What i do is:

Create a TextureAtlas from an XML file, so i can get a dictionary with the name of each region with a TextureRegion

```csharp
    public class TextureRegion
    {
        public Texture Texture;
        public int RegionX;
        public int RegionY;
        public int RegionWidth;
        public int RegionHeight;

        public TextureRegion()
        {}
        public TextureRegion(TextureRegion region)
        {
            this.Texture = region.Texture;
            this.RegionX = region.RegionX;
            this.RegionY = region.RegionY;
            this.RegionWidth = region.RegionWidth;
            this.RegionHeight = region.RegionHeight;
        }

        public IntRect IntRect => new IntRect(RegionX, RegionY, RegionWidth, RegionHeight);

        public TextureRegion[,] Split (int tileWidth, int tileHeight) 
        {
            var x = RegionX;
            var y = RegionY;
            var width = RegionWidth;
            var height = RegionHeight;

            var rows = height / tileHeight;
            var cols = width / tileWidth;

            var startX = x;
            var tiles = new TextureRegion[rows,cols];
            for (var row = 0; row < rows; row++, y += tileHeight) {
                x = startX;
                for (var col = 0; col < cols; col++, x += tileWidth) {
                    tiles[row,col] = new TextureRegion{Texture = Texture, RegionX = x,RegionY=  y, RegionWidth = tileWidth,RegionHeight = tileHeight};
                }
            }

            return tiles;
        }
    }
```

Then to create my entities, i take their ID (name), then i get the corresponding TextureRegion from the atlas and i create my sprite like this:

new Sprite(region.Texture, region.IntRect);

That is why i find it inefficient, since i want to reuse my base Texture loaded from the TextureAtlas class

And using an Image for the base texture, and one Texture per region will produce lof of texture swapping during rendering

**Comment by texus** [comment]
Well, you don't have to use the Picture class, you can just use the Texture and Sprite classes from SFML to draw things which I definately recommend to do the stuff that you described.

TGUI currently handles different textures in a naive and inefficient way. There is texture swapping going on in the c++ code the whole time, every draw call uses its own texture. Performance has never been my primary concern, as long as it is fast enough for normal usage it don't really matter to me. But if you want to render things like tilemaps then you should definately not rely on the Picture class.

**Comment by RUSshy** [comment]
What i wanted to make is a map editor, with panels that contains all the entities / tiles / items of my game (over 500 different sprites) with their animation too

I think what i will do is creating a custom widget, so it can fit my engine better :p, but i just need to figure out how ^^

**Comment by texus** [comment]
You could use the Canvas widget. You would draw the sprites to to the canvas and then draw this canvas to the panel. Since the Canvas is basically an sf::RenderTexture under the hood it is an extra draw call, but you can integrate sfml drawing inside tgui widgets like this.

**Comment by RUSshy** [comment]
I'll try with the Canvas, thanks :)
