### ISSUE TITLE
Widgets created via "tguiGui_loadWidgetsFromFile" will not have UserData

### ISSUE THREAD

**Issue by LLAW-A-LLAW** [texus/CTGUI#2]
I have this example .txt created with the gui-builder. It only has two buttons, one with and one without UserData.
[example.txt](https://github.com/texus/CTGUI/files/14888362/example.txt)
```
Renderer.1 {
}

Button.btnHasNot {
    Position = (10, 10);
    Renderer = &1;
    Text = "Has Not";
    TextSize = 13;
}

Button.btnHas {
    Position = (10, 40);
    Renderer = &1;
    Text = Has;
    TextSize = 13;
    UserData = datahere;
}
```

When loading it with `tguiGui_loadWidgetsFromFile` all the widgets load correctly, except when calling `tguiWidget_getUserData` a null pointer is always returned, regardless if the widget has UserData.

Calling `tguiWidget_hasUserData` does correctly detect widgets with UserData.

I do not have this issue when setting UserData with `tguiWidget_setUserData`.

Demonstration of this in C:
```
tguiGui_loadWidgetsFromFile(ui_gui, "example.txt", true);

size_t count; tguiWidget** widgets = tguiGui_getWidgets(ui_gui, &count);
for (unsigned int i = 0; i < count; i++) {
	char32_t* str = tguiWidget_getWidgetName(widgets[i]); char widget_name[255];
	for (unsigned int i = 0; *str != 0; str++) { sprintf(widget_name + i, "%c", *str); i++; }

	if (tguiWidget_hasUserData(widgets[i])) {
		void* userdata = tguiWidget_getUserData(widgets[i]);
		printf("%s\t'%x'\n", widget_name, userdata);
	}
	else {
		printf("%s\tnone\n", widget_name);
	}

	tguiWidget_free(widgets[i]);
}
```

Output from above demonstration:
```
btnHasNot       none
btnHas  '0'
```

I haven't been able to test this with TGUI, but I believe it's an issue with CTGUI.
Thank you in advance.

**Comment by texus** [comment]
In c++ the getUserData function is a template that needs to be given a type. In CTGUI I implemented setUserData and getUserData to always use a `void*` internally.

Loading the form happens in c++ and the data is stored as a string there. The tguiWidget_getUserData function fails to read it as it attempts to read a `void*` instead of as a string. I'll see if I can fix this.

**Comment by texus** [comment]
It should be fixed now. When the widget was loaded with `tguiGui_loadWidgetsFromFile`, you can now use the following code to read the user data:
```c
tguiUtf32 userdata = (tguiUtf32)tguiWidget_getUserData(widgets[i]);
```

Thanks for providing such a detailed description btw, it allowed to quickly identify the bug and helped testing that the code works now.

**Comment by LLAW-A-LLAW** [comment]
Thank you for such a quick fix! I can confirm this is fixed on my side too.
